services:
  safedriver-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: safedriver-front
    ports:
      - "3000:3000"
    networks:
      - safedriver_network
    volumes:
      - ./app:/app
    environment:
      - NEXT_PUBLIC_URL_API=http://localhost:8080
    command: /start.sh

networks:
  safedriver_network:
    driver: bridge